# Generated by Django 5.2.8 on 2025-11-25 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOffer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'cost',
                    models.IntegerField(
                        default=100,
                        help_text='Enter item cost',
                        verbose_name='Item cost',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        help_text='Enter item',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='items.items',
                        verbose_name='item',
                    ),
                ),
            ],
            options={
                'verbose_name': 'seller offer',
                'verbose_name_plural': 'sellers offers',
            },
        ),
    ]
