# Generated by Django 5.2.8 on 2025-11-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Enter location name',
                        max_length=150,
                        verbose_name='Location name',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Enter location slug',
                        max_length=150,
                        verbose_name='Location slug',
                    ),
                ),
            ],
        ),
    ]
