# Generated by Django 5.2.8 on 2025-11-25 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rarity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Enter item name',
                        max_length=100,
                        verbose_name='item name',
                    ),
                ),
                (
                    'damage',
                    models.IntegerField(
                        default=1,
                        help_text='Enter damage when used as a weapon',
                        verbose_name='damage when used as a weapon',
                    ),
                ),
                (
                    'rarity',
                    models.ForeignKey(
                        help_text='Enter item rarity',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='rarity.rarity',
                        verbose_name='rarity',
                    ),
                ),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
    ]
