# Generated by Django 5.2.8 on 2025-11-26 18:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('locations', '0001_initial'),
        ('sellers_offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPlayerCharacter',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Enter entity name',
                        max_length=100,
                        verbose_name='entity name',
                    ),
                ),
                (
                    'max_hp',
                    models.IntegerField(
                        default=100,
                        help_text='Enter entity max health',
                        verbose_name='entity max health',
                    ),
                ),
                (
                    'hp',
                    models.IntegerField(
                        default=100,
                        help_text='Enter entity current health',
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name='entity current health',
                    ),
                ),
                (
                    'max_mana',
                    models.IntegerField(
                        default=20,
                        help_text='Enter entity max mana',
                        verbose_name='entity max mana',
                    ),
                ),
                (
                    'mana',
                    models.IntegerField(
                        default=20,
                        help_text='Enter entity current mana',
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name='entity current mana',
                    ),
                ),
                (
                    'base_damage',
                    models.IntegerField(
                        default=10,
                        help_text='Enter the damage the entity causes',
                        verbose_name='entity damage',
                    ),
                ),
                (
                    'is_in_battle',
                    models.BooleanField(
                        default=False,
                        help_text='Specify whether the entity is in combat',
                        verbose_name='is entity in battle',
                    ),
                ),
                (
                    'current_location',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_entities',
                        to='locations.location',
                        verbose_name='entity location',
                    ),
                ),
                (
                    'items_to_drop',
                    models.ManyToManyField(
                        blank=True, to='items.items', verbose_name='item'
                    ),
                ),
            ],
            options={
                'verbose_name': 'npc',
                'verbose_name_plural': 'npcs',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Enter entity name',
                        max_length=100,
                        verbose_name='entity name',
                    ),
                ),
                (
                    'max_hp',
                    models.IntegerField(
                        default=100,
                        help_text='Enter entity max health',
                        verbose_name='entity max health',
                    ),
                ),
                (
                    'hp',
                    models.IntegerField(
                        default=100,
                        help_text='Enter entity current health',
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name='entity current health',
                    ),
                ),
                (
                    'max_mana',
                    models.IntegerField(
                        default=20,
                        help_text='Enter entity max mana',
                        verbose_name='entity max mana',
                    ),
                ),
                (
                    'mana',
                    models.IntegerField(
                        default=20,
                        help_text='Enter entity current mana',
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name='entity current mana',
                    ),
                ),
                (
                    'base_damage',
                    models.IntegerField(
                        default=10,
                        help_text='Enter the damage the entity causes',
                        verbose_name='entity damage',
                    ),
                ),
                (
                    'is_in_battle',
                    models.BooleanField(
                        default=False,
                        help_text='Specify whether the entity is in combat',
                        verbose_name='is entity in battle',
                    ),
                ),
                (
                    'current_location',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_entities',
                        to='locations.location',
                        verbose_name='entity location',
                    ),
                ),
                (
                    'inventory',
                    models.ManyToManyField(
                        blank=True,
                        related_name='player_inventory',
                        to='items.items',
                        verbose_name='item',
                    ),
                ),
                (
                    'start_location',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='locations.location',
                        verbose_name='start location',
                    ),
                ),
                (
                    'weapon',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='equipped_by_player',
                        to='items.items',
                        verbose_name='equipped weapon',
                    ),
                ),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Enter entity name',
                        max_length=100,
                        verbose_name='Entity name',
                    ),
                ),
                (
                    'offers',
                    models.ManyToManyField(
                        blank=True,
                        to='sellers_offers.selleroffer',
                        verbose_name='offer',
                    ),
                ),
            ],
            options={
                'verbose_name': 'seller',
                'verbose_name_plural': 'sellers',
            },
        ),
    ]
