# Generated by Django 5.2.8 on 2025-11-27 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(
                blank=True,
                help_text='The user account associated with this player',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='player_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
