# Generated by Django 5.2.8 on 2025-11-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Enter rarity name',
                        max_length=100,
                        verbose_name='Rarity name',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Enter slug for rarity',
                        max_length=100,
                        verbose_name='Rarity slug',
                    ),
                ),
            ],
            options={
                'verbose_name': 'rarity',
                'verbose_name_plural': 'list of rarities',
            },
        ),
    ]
